export type PracticeLetter = 'A' | 'B' | 'C' | 'D';

export interface PracticeOption {
  letter: PracticeLetter;
  text: string;
}

export interface PracticeQuestion {
  questionNo: number;
  part: 5 | 6 | 7;
  question: string;
  options: PracticeOption[];
  answer: PracticeLetter;
  explanation: string;
  translation?: string;
  vocabulary?: string[];
}

export const PART5_PRACTICE_TEST_ID = 'part5-set-01';
export const PART5_PRACTICE_TEST_TITLE = '2022 Test 10 Part 5';
export const PART5_2022_TEST_3_ID = 'part5-2022-test-3';
export const PART5_2022_TEST_3_TITLE = '2022 Test 3 Part 5';
export const PART5_2022_TEST_4_ID = 'part5-2022-test-4';
export const PART5_2022_TEST_4_TITLE = '2022 Test 4 Part 5';

export const PART5_PRACTICE_SET_01: PracticeQuestion[] = [
  {
    questionNo: 101,
    part: 5,
    question: 'A _____ salesperson assisted Ms. Han with choosing a new computer.',
    options: [
      { letter: 'A', text: 'help' },
      { letter: 'B', text: 'helpfully' },
      { letter: 'C', text: 'helpful' },
      { letter: 'D', text: 'helped' },
    ],
    answer: 'C',
    explanation: 'Chỗ trống đứng ngay trước danh từ "salesperson", nên cần một tính từ để bổ nghĩa cho danh từ đó. "Helpful" là tính từ nghĩa là hay giúp đỡ/hữu ích. "Help" là động từ/danh từ, "helpfully" là trạng từ, còn "helped" là động từ quá khứ/phân từ nên không phù hợp vị trí này.',
    translation: 'Một nhân viên bán hàng hay giúp đỡ đã hỗ trợ cô Han chọn một chiếc máy tính mới.',
    vocabulary: ['assist (v): hỗ trợ', 'salesperson (n): nhân viên bán hàng'],
  },
  {
    questionNo: 102,
    part: 5,
    question: 'Author Daniel Aiduk _____ gives talks at national writing conferences.',
    options: [
      { letter: 'A', text: 'gradually' },
      { letter: 'B', text: 'longer' },
      { letter: 'C', text: 'together' },
      { letter: 'D', text: 'regularly' },
    ],
    answer: 'D',
    explanation: 'Câu đã có chủ ngữ "Author Daniel Aiduk" và động từ "gives"; chỗ trống cần trạng từ bổ nghĩa cho mức độ/tần suất của hành động. "Regularly" nghĩa là thường xuyên, hợp với ngữ cảnh thuyết trình tại các hội nghị. Các đáp án còn lại không hợp nghĩa trong câu.',
    translation: 'Tác giả Daniel Aiduk thường xuyên thuyết trình tại các hội nghị viết văn quốc gia.',
    vocabulary: ['conference (n): hội nghị', 'national (adj): thuộc quốc gia, cấp quốc gia'],
  },
  {
    questionNo: 103,
    part: 5,
    question: 'Mr. Kohl has a great deal of _____ performing cost analysis tasks.',
    options: [
      { letter: 'A', text: 'experience' },
      { letter: 'B', text: 'experienced' },
      { letter: 'C', text: 'experiencing' },
      { letter: 'D', text: 'experiencer' },
    ],
    answer: 'A',
    explanation: 'Cụm "a great deal of" thường đi với danh từ không đếm được để chỉ số lượng lớn. "Experience" ở đây là danh từ nghĩa là kinh nghiệm. "Experienced" là tính từ, "experiencing" là V-ing, còn "experiencer" không hợp nghĩa trong ngữ cảnh này.',
    translation: 'Ông Kohl có nhiều kinh nghiệm thực hiện các nhiệm vụ phân tích chi phí.',
    vocabulary: ['analysis (n): sự phân tích', 'task (n): nhiệm vụ', 'perform (v): thực hiện'],
  },
  {
    questionNo: 104,
    part: 5,
    question: 'To make an _____, clients can click on "Schedule" at the top right corner of the home page.',
    options: [
      { letter: 'A', text: 'example' },
      { letter: 'B', text: 'option' },
      { letter: 'C', text: 'individual' },
      { letter: 'D', text: 'appointment' },
    ],
    answer: 'D',
    explanation: 'Cụm đúng là "make an appointment", nghĩa là đặt lịch hẹn. Từ "Schedule" trên trang web cũng là dấu hiệu ngữ cảnh rất mạnh. Các danh từ còn lại có thể đúng ngữ pháp sau "an", nhưng không tạo cụm nghĩa tự nhiên với "make" trong câu này.',
    translation: 'Để đặt lịch hẹn, khách hàng có thể nhấp vào "Schedule" ở góc trên cùng bên phải của trang chủ.',
    vocabulary: ['appointment (n): cuộc hẹn, lịch hẹn', 'client (n): khách hàng'],
  },
  {
    questionNo: 105,
    part: 5,
    question: 'The used coffee grounds should be disposed of at the end of _____ business day.',
    options: [
      { letter: 'A', text: 'now' },
      { letter: 'B', text: 'each' },
      { letter: 'C', text: 'whose' },
      { letter: 'D', text: 'and' },
    ],
    answer: 'B',
    explanation: 'Sau chỗ trống là cụm danh từ số ít "business day". "Each" đứng trước danh từ số ít để diễn tả "mỗi". Cụm "at the end of each business day" nghĩa là vào cuối mỗi ngày làm việc.',
    translation: 'Bã cà phê đã sử dụng nên được vứt bỏ vào cuối mỗi ngày làm việc.',
    vocabulary: ['coffee grounds (n): bã cà phê', 'dispose of (phr.v): vứt bỏ', 'business day (n): ngày làm việc'],
  },
  {
    questionNo: 106,
    part: 5,
    question: "Our company's efforts to hire new workers have intensified _____ so many employees have recently retired.",
    options: [
      { letter: 'A', text: 'because' },
      { letter: 'B', text: 'although' },
      { letter: 'C', text: 'instead' },
      { letter: 'D', text: 'unless' },
    ],
    answer: 'A',
    explanation: 'Mệnh đề sau chỗ trống nêu lý do vì sao công ty tăng cường tuyển người mới: nhiều nhân viên gần đây đã nghỉ hưu. Vì vậy cần liên từ chỉ nguyên nhân "because". "Although" chỉ nhượng bộ, "unless" chỉ điều kiện phủ định, "instead" không nối hai mệnh đề theo cách này.',
    translation: 'Những nỗ lực tuyển nhân công mới của công ty chúng tôi đã tăng lên vì gần đây rất nhiều nhân viên đã nghỉ hưu.',
    vocabulary: ['effort (n): nỗ lực', 'intensify (v): tăng cường', 'retire (v): nghỉ hưu'],
  },
  {
    questionNo: 107,
    part: 5,
    question: 'The occurrence of heavy rains during the month of May is fairly _____.',
    options: [
      { letter: 'A', text: 'predict' },
      { letter: 'B', text: 'predicts' },
      { letter: 'C', text: 'predicting' },
      { letter: 'D', text: 'predictable' },
    ],
    answer: 'D',
    explanation: 'Sau động từ liên kết "is" và trạng từ "fairly" cần một tính từ làm bổ ngữ. "Predictable" là tính từ nghĩa là có thể dự đoán được. "Predict/predicts" là động từ, "predicting" là V-ing nên không phù hợp.',
    translation: 'Sự xuất hiện của những trận mưa lớn trong tháng 5 là khá dễ dự đoán.',
    vocabulary: ['occurrence (n): sự xuất hiện, việc xảy ra', 'fairly (adv): khá', 'predict (v): dự đoán'],
  },
  {
    questionNo: 108,
    part: 5,
    question: 'Remind customers to return their rental car _____ a full tank of fuel.',
    options: [
      { letter: 'A', text: 'with' },
      { letter: 'B', text: 'from' },
      { letter: 'C', text: 'except' },
      { letter: 'D', text: 'toward' },
    ],
    answer: 'A',
    explanation: 'Cần giới từ diễn tả tình trạng kèm theo khi trả xe: trả xe "với" một bình nhiên liệu đầy. Vì vậy chọn "with". Các giới từ còn lại không tạo nghĩa tự nhiên với "return a car ... a full tank".',
    translation: 'Hãy nhắc khách hàng trả lại xe thuê của họ với một bình nhiên liệu đầy.',
    vocabulary: ['rental car (n): xe thuê', 'tank (n): bình, thùng chứa', 'remind (v): nhắc nhở'],
  },
  {
    questionNo: 109,
    part: 5,
    question: '_____ the winter season, Serina Builders will once again offer roof installations and repairs.',
    options: [
      { letter: 'A', text: 'Such as' },
      { letter: 'B', text: 'Moreover' },
      { letter: 'C', text: 'After' },
      { letter: 'D', text: 'Whereas' },
    ],
    answer: 'C',
    explanation: 'Sau chỗ trống là cụm danh từ "the winter season", nên cần một giới từ/cụm nối phù hợp. "After the winter season" nghĩa là sau mùa đông. "Moreover" là trạng từ liên kết, "whereas" nối mệnh đề, còn "such as" dùng để nêu ví dụ.',
    translation: 'Sau mùa đông, Serina Builders sẽ một lần nữa cung cấp dịch vụ lắp đặt và sửa chữa mái nhà.',
    vocabulary: ['installation (n): sự lắp đặt', 'repair (n/v): sửa chữa', 'offer (v): cung cấp'],
  },
  {
    questionNo: 110,
    part: 5,
    question: 'The lights in the cinema _____ before a movie begins.',
    options: [
      { letter: 'A', text: 'dim' },
      { letter: 'B', text: 'dimming' },
      { letter: 'C', text: 'dimmer' },
      { letter: 'D', text: 'dims' },
    ],
    answer: 'A',
    explanation: 'Câu thiếu động từ chính. Chủ ngữ "The lights" là số nhiều, nên động từ hiện tại đơn không thêm -s: "dim". "Dimming" không làm động từ chính nếu không có trợ động từ, "dimmer" là danh từ/tính từ so sánh, "dims" dùng với chủ ngữ số ít.',
    translation: 'Đèn trong rạp chiếu phim mờ đi trước khi một bộ phim bắt đầu.',
    vocabulary: ['dim (v): mờ đi, làm mờ', 'cinema (n): rạp chiếu phim'],
  },
  {
    questionNo: 111,
    part: 5,
    question: 'When scheduling a meeting, please be _____ of colleagues in other time zones.',
    options: [
      { letter: 'A', text: 'significant' },
      { letter: 'B', text: 'mindful' },
      { letter: 'C', text: 'exclusive' },
      { letter: 'D', text: 'serious' },
    ],
    answer: 'B',
    explanation: 'Cụm tự nhiên là "be mindful of", nghĩa là lưu ý/quan tâm đến điều gì. Ngữ cảnh là khi xếp lịch họp cần để ý đồng nghiệp ở múi giờ khác. Các tính từ còn lại không đi với "of" theo nghĩa phù hợp trong câu này.',
    translation: 'Khi lên lịch họp, hãy lưu ý đến các đồng nghiệp ở múi giờ khác.',
    vocabulary: ['schedule (v/n): lên lịch; lịch trình', 'colleague (n): đồng nghiệp', 'time zone (n): múi giờ'],
  },
  {
    questionNo: 112,
    part: 5,
    question: "Greentrim's product sales rose _____ following the introduction of its new shipping policy.",
    options: [
      { letter: 'A', text: 'sharp' },
      { letter: 'B', text: 'sharper' },
      { letter: 'C', text: 'sharply' },
      { letter: 'D', text: 'sharpest' },
    ],
    answer: 'C',
    explanation: 'Động từ chính là "rose" (đã tăng). Chỗ trống cần trạng từ để bổ nghĩa cho động từ này. "Sharply" là trạng từ nghĩa là mạnh/đột ngột. "Sharp", "sharper", "sharpest" là các dạng tính từ nên không bổ nghĩa trực tiếp cho động từ "rose".',
    translation: 'Doanh số sản phẩm của Greentrim đã tăng mạnh sau khi áp dụng chính sách vận chuyển mới.',
    vocabulary: ['rise/rose (v): tăng', 'introduction (n): sự giới thiệu, sự áp dụng', 'policy (n): chính sách'],
  },
  {
    questionNo: 113,
    part: 5,
    question: 'Please _____ Hearnshaw for all your home appliance needs.',
    options: [
      { letter: 'A', text: 'assemble' },
      { letter: 'B', text: 'balance' },
      { letter: 'C', text: 'share' },
      { letter: 'D', text: 'consider' },
    ],
    answer: 'D',
    explanation: 'Sau "Please" cần động từ nguyên mẫu. Về nghĩa, "consider Hearnshaw for..." nghĩa là hãy cân nhắc/chọn Hearnshaw cho các nhu cầu đồ gia dụng. Các động từ còn lại không hợp ngữ cảnh quảng cáo/dịch vụ.',
    translation: 'Hãy cân nhắc Hearnshaw cho tất cả các nhu cầu về thiết bị gia dụng của bạn.',
    vocabulary: ['consider (v): cân nhắc, xem xét', 'appliance (n): thiết bị gia dụng'],
  },
  {
    questionNo: 114,
    part: 5,
    question: 'Monday will be the best day for _____ to clean the carpet in the lobby.',
    options: [
      { letter: 'A', text: 'we' },
      { letter: 'B', text: 'us' },
      { letter: 'C', text: 'ours' },
      { letter: 'D', text: 'ourselves' },
    ],
    answer: 'B',
    explanation: 'Cấu trúc là "for + tân ngữ + to V": for us to clean. Sau giới từ "for" cần đại từ tân ngữ, nên chọn "us". "We" là chủ ngữ, "ours" là đại từ sở hữu, "ourselves" là đại từ phản thân.',
    translation: 'Thứ Hai sẽ là ngày tốt nhất để chúng tôi làm sạch thảm ở sảnh.',
    vocabulary: ['carpet (n): thảm', 'lobby (n): sảnh'],
  },
  {
    questionNo: 115,
    part: 5,
    question: 'Hikers, _____ to explore the newly opened trails, have been visiting Millar Nature Reserve in record numbers.',
    options: [
      { letter: 'A', text: 'tender' },
      { letter: 'B', text: 'bright' },
      { letter: 'C', text: 'vast' },
      { letter: 'D', text: 'eager' },
    ],
    answer: 'D',
    explanation: 'Cụm đúng là "eager to V", nghĩa là háo hức muốn làm gì. Câu có cụm "to explore", nên cần tính từ đi được với "to V". "Tender", "bright", "vast" không tạo cụm nghĩa phù hợp.',
    translation: 'Những người đi bộ đường dài, háo hức khám phá các con đường mòn mới mở, đã đến Khu bảo tồn Thiên nhiên Millar với số lượng kỷ lục.',
    vocabulary: ['hiker (n): người đi bộ đường dài', 'trail (n): đường mòn', 'nature reserve (n): khu bảo tồn thiên nhiên'],
  },
  {
    questionNo: 116,
    part: 5,
    question: 'KOHW _____ Jena Johnson will be promoted to news anchor when Dana Wagner retires.',
    options: [
      { letter: 'A', text: 'reporter' },
      { letter: 'B', text: 'reporting' },
      { letter: 'C', text: 'to report' },
      { letter: 'D', text: 'will report' },
    ],
    answer: 'A',
    explanation: '"KOHW reporter Jena Johnson" là một cụm danh từ chỉ chức danh + tên riêng: phóng viên Jena Johnson của KOHW. Câu đã có động từ chính "will be promoted", nên không chọn các dạng động từ như "reporting", "to report" hoặc "will report".',
    translation: 'Phóng viên Jena Johnson của KOHW sẽ được thăng chức làm người dẫn tin khi Dana Wagner nghỉ hưu.',
    vocabulary: ['reporter (n): phóng viên', 'promote (v): thăng chức', 'news anchor (n): người dẫn tin'],
  },
  {
    questionNo: 117,
    part: 5,
    question: "Residents _____ raised concerns about the project's impact on traffic congestion.",
    options: [
      { letter: 'A', text: 'extremely' },
      { letter: 'B', text: 'unlikely' },
      { letter: 'C', text: 'densely' },
      { letter: 'D', text: 'primarily' },
    ],
    answer: 'D',
    explanation: 'Câu cần trạng từ bổ nghĩa cho hành động "raised concerns", diễn tả cư dân chủ yếu nêu lo ngại về vấn đề nào. "Primarily" nghĩa là chủ yếu. Các trạng từ còn lại không hợp nghĩa với hành động nêu lo ngại trong câu này.',
    translation: 'Cư dân chủ yếu nêu lo ngại về tác động của dự án đối với tình trạng tắc nghẽn giao thông.',
    vocabulary: ['resident (n): cư dân', 'concern (n): mối lo ngại', 'traffic congestion (n): tắc nghẽn giao thông'],
  },
  {
    questionNo: 118,
    part: 5,
    question: '_____ your Fromo grocery order is placed before 10:00 A.M., it will be delivered the same day.',
    options: [
      { letter: 'A', text: 'That' },
      { letter: 'B', text: 'Such' },
      { letter: 'C', text: 'As long as' },
      { letter: 'D', text: 'In spite of' },
    ],
    answer: 'C',
    explanation: 'Câu diễn tả điều kiện: nếu/miễn là đơn hàng được đặt trước 10 giờ thì sẽ giao cùng ngày. "As long as + clause" nghĩa là miễn là. "In spite of" đi với danh từ/V-ing và chỉ nhượng bộ, không phù hợp cấu trúc này.',
    translation: 'Miễn là đơn hàng tạp hóa Fromo của bạn được đặt trước 10 giờ sáng, hàng sẽ được giao ngay trong ngày.',
    vocabulary: ['grocery order (n): đơn hàng tạp hóa', 'deliver (v): giao hàng'],
  },
  {
    questionNo: 119,
    part: 5,
    question: 'The finance department will be _____ a lunch-and-learn session on Wednesday.',
    options: [
      { letter: 'A', text: 'contacting' },
      { letter: 'B', text: 'collecting' },
      { letter: 'C', text: 'meeting' },
      { letter: 'D', text: 'holding' },
    ],
    answer: 'D',
    explanation: 'Cụm "hold a session/meeting/event" nghĩa là tổ chức một buổi họp/sự kiện. Câu dùng tương lai tiếp diễn "will be holding". Các động từ "contacting", "collecting", "meeting" không đi tự nhiên với "a session" theo nghĩa tổ chức.',
    translation: 'Bộ phận tài chính sẽ tổ chức một buổi vừa ăn trưa vừa học vào thứ Tư.',
    vocabulary: ['finance department (n): phòng tài chính', 'session (n): buổi, phiên'],
  },
  {
    questionNo: 120,
    part: 5,
    question: '_____ clothing must be worn by all personnel entering the construction zone.',
    options: [
      { letter: 'A', text: 'Protective' },
      { letter: 'B', text: 'Protecting' },
      { letter: 'C', text: 'Protect' },
      { letter: 'D', text: 'Protects' },
    ],
    answer: 'A',
    explanation: 'Chỗ trống đứng trước danh từ "clothing", nên cần tính từ bổ nghĩa cho danh từ. "Protective clothing" là cụm cố định nghĩa là quần áo bảo hộ. "Protect" và "protects" là động từ, "protecting" không tự nhiên bằng tính từ "protective" trong cụm này.',
    translation: 'Quần áo bảo hộ phải được mặc bởi tất cả nhân viên vào khu vực xây dựng.',
    vocabulary: ['protective clothing (n): quần áo bảo hộ', 'personnel (n): nhân viên', 'construction zone (n): khu vực xây dựng'],
  },
  {
    questionNo: 121,
    part: 5,
    question: 'At the Star Elite membership level, most flight changes can be made _____ incurring a rebooking fee.',
    options: [
      { letter: 'A', text: 'along' },
      { letter: 'B', text: 'without' },
      { letter: 'C', text: 'until' },
      { letter: 'D', text: 'inside' },
    ],
    answer: 'B',
    explanation: 'Sau chỗ trống là V-ing "incurring", và nghĩa cần là không phải chịu phí đặt lại. "Without + V-ing" là cấu trúc đúng: without incurring a fee. Các giới từ còn lại không tạo nghĩa phù hợp.',
    translation: 'Ở cấp độ thành viên Star Elite, hầu hết thay đổi chuyến bay có thể được thực hiện mà không phải chịu phí đặt lại.',
    vocabulary: ['membership (n): tư cách thành viên', 'incur (v): gánh chịu', 'rebooking fee (n): phí đặt lại'],
  },
  {
    questionNo: 122,
    part: 5,
    question: 'Any letter _____ sensitive information should be sent using a courier service.',
    options: [
      { letter: 'A', text: 'contains' },
      { letter: 'B', text: 'containing' },
      { letter: 'C', text: 'will contain' },
      { letter: 'D', text: 'has contained' },
    ],
    answer: 'B',
    explanation: 'Đây là dạng rút gọn mệnh đề quan hệ chủ động: "Any letter that contains sensitive information" rút gọn thành "Any letter containing sensitive information". Câu đã có động từ chính "should be sent", nên không chọn các dạng động từ chia như "contains/will contain/has contained".',
    translation: 'Bất kỳ lá thư nào chứa thông tin nhạy cảm nên được gửi bằng dịch vụ chuyển phát nhanh.',
    vocabulary: ['sensitive information (n): thông tin nhạy cảm', 'courier service (n): dịch vụ chuyển phát nhanh'],
  },
  {
    questionNo: 123,
    part: 5,
    question: 'Abelos Café sources its vegetables and fruit from local farms _____ possible.',
    options: [
      { letter: 'A', text: 'anyhow' },
      { letter: 'B', text: 'whenever' },
      { letter: 'C', text: 'once' },
      { letter: 'D', text: 'very' },
    ],
    answer: 'B',
    explanation: 'Cụm rút gọn "whenever possible" nghĩa là bất cứ khi nào có thể. Câu muốn nói quán lấy rau củ và trái cây từ nông trại địa phương khi có thể. "Anyhow", "once" và "very" không tạo cụm đúng với "possible".',
    translation: 'Abelos Café lấy rau củ và trái cây từ các nông trại địa phương bất cứ khi nào có thể.',
    vocabulary: ['source (v): lấy nguồn/cung ứng từ', 'local farm (n): nông trại địa phương', 'whenever possible: bất cứ khi nào có thể'],
  },
  {
    questionNo: 124,
    part: 5,
    question: 'Demand for the Waterlace running shoes was so high that the store owner set a _____ of two pairs per customer.',
    options: [
      { letter: 'A', text: 'limit' },
      { letter: 'B', text: 'price' },
      { letter: 'C', text: 'supply' },
      { letter: 'D', text: 'procedure' },
    ],
    answer: 'A',
    explanation: 'Cấu trúc "set a limit of..." nghĩa là đặt giới hạn là bao nhiêu. Ngữ cảnh nhu cầu quá cao nên chủ cửa hàng giới hạn mỗi khách hàng hai đôi. Các danh từ khác không hợp với "of two pairs per customer".',
    translation: 'Nhu cầu đối với giày chạy bộ Waterlace cao đến mức chủ cửa hàng đặt giới hạn hai đôi cho mỗi khách hàng.',
    vocabulary: ['demand (n): nhu cầu', 'set a limit: đặt giới hạn', 'per customer: mỗi khách hàng'],
  },
  {
    questionNo: 125,
    part: 5,
    question: 'The new security camera adjusts _____ in such a way that it can record quality video at night.',
    options: [
      { letter: 'A', text: 'himself' },
      { letter: 'B', text: 'oneself' },
      { letter: 'C', text: 'itself' },
      { letter: 'D', text: 'herself' },
    ],
    answer: 'C',
    explanation: 'Chủ ngữ là "The new security camera", tương ứng với đại từ "it". Khi nói camera tự điều chỉnh, cần đại từ phản thân "itself". "Himself/herself" dùng cho người, "oneself" dùng chung chung nhưng không phù hợp chủ ngữ cụ thể này.',
    translation: 'Camera an ninh mới tự điều chỉnh theo cách có thể quay video chất lượng vào ban đêm.',
    vocabulary: ['security camera (n): camera an ninh', 'adjust (v): điều chỉnh', 'record (v): ghi/quay lại'],
  },
  {
    questionNo: 126,
    part: 5,
    question: "Contact Ms. Meyer if you would like a hard copy of the budget analysis _____ during the president's presentation.",
    options: [
      { letter: 'A', text: 'occurred' },
      { letter: 'B', text: 'mentioned' },
      { letter: 'C', text: 'learned' },
      { letter: 'D', text: 'served' },
    ],
    answer: 'B',
    explanation: 'Cụm sau danh từ "budget analysis" là rút gọn mệnh đề quan hệ bị động: "the budget analysis that was mentioned during..." nghĩa là bản phân tích ngân sách được đề cập trong bài thuyết trình. Vì vậy chọn "mentioned".',
    translation: 'Hãy liên hệ bà Meyer nếu bạn muốn bản in của phân tích ngân sách được đề cập trong buổi thuyết trình của chủ tịch.',
    vocabulary: ['hard copy (n): bản in', 'budget analysis (n): phân tích ngân sách', 'presentation (n): bài thuyết trình'],
  },
  {
    questionNo: 127,
    part: 5,
    question: "Saul's Pizzeria changed its menu options after receiving _____ negative customer feedback.",
    options: [
      { letter: 'A', text: 'increase' },
      { letter: 'B', text: 'increases' },
      { letter: 'C', text: 'to increase' },
      { letter: 'D', text: 'increasingly' },
    ],
    answer: 'D',
    explanation: 'Chỗ trống đứng trước tính từ "negative", nên cần trạng từ để bổ nghĩa cho tính từ đó. "Increasingly negative feedback" nghĩa là phản hồi ngày càng tiêu cực. Các đáp án A/B/C là danh từ/động từ/cụm to-V nên không đúng vị trí.',
    translation: "Saul's Pizzeria đã thay đổi các lựa chọn thực đơn sau khi nhận được phản hồi ngày càng tiêu cực từ khách hàng.",
    vocabulary: ['feedback (n): phản hồi', 'increasingly (adv): ngày càng'],
  },
  {
    questionNo: 128,
    part: 5,
    question: 'Topticolor produces devices intended for use by _____ photographers.',
    options: [
      { letter: 'A', text: 'visible' },
      { letter: 'B', text: 'eventual' },
      { letter: 'C', text: 'amateur' },
      { letter: 'D', text: 'necessary' },
    ],
    answer: 'C',
    explanation: 'Chỗ trống bổ nghĩa cho danh từ "photographers". Về nghĩa, thiết bị được sản xuất để dùng bởi "amateur photographers" là các nhiếp ảnh gia nghiệp dư. Các tính từ còn lại không tạo cụm danh từ tự nhiên trong ngữ cảnh sản phẩm.',
    translation: 'Topticolor sản xuất các thiết bị dành cho các nhiếp ảnh gia nghiệp dư.',
    vocabulary: ['produce (v): sản xuất', 'device (n): thiết bị', 'amateur photographer (n): nhiếp ảnh gia nghiệp dư'],
  },
  {
    questionNo: 129,
    part: 5,
    question: 'The study of consumer behavior will be repeated in order to ensure the _____ of the results.',
    options: [
      { letter: 'A', text: 'rely' },
      { letter: 'B', text: 'relies' },
      { letter: 'C', text: 'reliable' },
      { letter: 'D', text: 'reliability' },
    ],
    answer: 'D',
    explanation: 'Sau mạo từ "the" và trước cụm "of the results" cần một danh từ. "Reliability" là danh từ nghĩa là độ tin cậy. "Rely/relies" là động từ, còn "reliable" là tính từ.',
    translation: 'Nghiên cứu về hành vi người tiêu dùng sẽ được lặp lại để đảm bảo độ tin cậy của kết quả.',
    vocabulary: ['consumer behavior (n): hành vi người tiêu dùng', 'repeat (v): lặp lại', 'reliability (n): độ tin cậy'],
  },
  {
    questionNo: 130,
    part: 5,
    question: 'Check e-mail _____ throughout the day to make sure important client communications are not overlooked.',
    options: [
      { letter: 'A', text: 'artificially' },
      { letter: 'B', text: 'periodically' },
      { letter: 'C', text: 'reluctantly' },
      { letter: 'D', text: 'simultaneously' },
    ],
    answer: 'B',
    explanation: 'Cần trạng từ bổ nghĩa cho hành động "Check e-mail" và hợp nghĩa với "throughout the day". "Periodically" nghĩa là định kỳ/thỉnh thoảng theo từng khoảng thời gian, đúng với việc kiểm tra email trong ngày.',
    translation: 'Hãy kiểm tra email định kỳ trong ngày để đảm bảo các trao đổi quan trọng của khách hàng không bị bỏ sót.',
    vocabulary: ['throughout (prep/adv): xuyên suốt', 'overlook (v): bỏ sót, không chú ý', 'client communication (n): trao đổi với khách hàng'],
  },
];

export const PART5_2022_TEST_3_SET: PracticeQuestion[] = [
  {
    questionNo: 101,
    part: 5,
    question: 'Vantage Automotive Design has recently _____ with the Pallax Company.',
    options: [
      { letter: 'A', text: 'merge' },
      { letter: 'B', text: 'merger' },
      { letter: 'C', text: 'merged' },
      { letter: 'D', text: 'merging' },
    ],
    answer: 'C',
    explanation: 'Câu dùng thì hiện tại hoàn thành: "has recently + V3/V-ed". Động từ "merge" khi chia V3/V-ed là "merged". "Merger" là danh từ, "merge" là nguyên mẫu, còn "merging" là V-ing nên không đi ngay sau "has" trong cấu trúc này.',
    translation: 'Vantage Automotive Design gần đây đã sáp nhập với Công ty Pallax.',
    vocabulary: ['merge (v): sáp nhập', 'merger (n): sự sáp nhập', 'recently (adv): gần đây'],
  },
  {
    questionNo: 102,
    part: 5,
    question: 'Rain is predicted this weekend, _____ the office picnic will have to be postponed.',
    options: [
      { letter: 'A', text: 'so' },
      { letter: 'B', text: 'for' },
      { letter: 'C', text: 'but' },
      { letter: 'D', text: 'nor' },
    ],
    answer: 'A',
    explanation: 'Mệnh đề trước nêu nguyên nhân: cuối tuần dự báo có mưa. Mệnh đề sau nêu kết quả: buổi picnic phải hoãn. Vì vậy cần liên từ chỉ kết quả "so". "But" chỉ tương phản, "nor" dùng trong cấu trúc phủ định, "for" ít dùng và mang sắc thái giải thích nguyên nhân ngược chiều.',
    translation: 'Dự báo cuối tuần này sẽ có mưa, vì vậy buổi dã ngoại của văn phòng sẽ phải hoãn lại.',
    vocabulary: ['predict (v): dự đoán', 'picnic (n): buổi dã ngoại', 'postpone (v): hoãn lại'],
  },
  {
    questionNo: 103,
    part: 5,
    question: 'Use an alternative shipping firm if Greer Freight is unable to expedite delivery of _____ order.',
    options: [
      { letter: 'A', text: 'you' },
      { letter: 'B', text: 'your' },
      { letter: 'C', text: 'yours' },
      { letter: 'D', text: 'yourselves' },
    ],
    answer: 'B',
    explanation: 'Chỗ trống đứng trước danh từ "order", nên cần tính từ sở hữu để bổ nghĩa cho danh từ. "Your order" nghĩa là đơn hàng của bạn. "You" là đại từ chủ/tân ngữ, "yours" là đại từ sở hữu đứng độc lập, "yourselves" là đại từ phản thân.',
    translation: 'Hãy dùng một công ty vận chuyển thay thế nếu Greer Freight không thể giao nhanh đơn hàng của bạn.',
    vocabulary: ['alternative (adj): thay thế', 'shipping firm (n): công ty vận chuyển', 'expedite (v): xúc tiến, làm nhanh'],
  },
  {
    questionNo: 104,
    part: 5,
    question: 'The cafeteria is featuring dishes _____ different regions of the world this week.',
    options: [
      { letter: 'A', text: 'over' },
      { letter: 'B', text: 'through' },
      { letter: 'C', text: 'into' },
      { letter: 'D', text: 'from' },
    ],
    answer: 'D',
    explanation: 'Cần giới từ chỉ nguồn gốc/xuất xứ của các món ăn. "Dishes from different regions" nghĩa là các món ăn đến từ những vùng khác nhau. Các giới từ còn lại không diễn tả đúng quan hệ nguồn gốc trong câu.',
    translation: 'Quán ăn tự phục vụ tuần này sẽ giới thiệu các món ăn từ nhiều vùng khác nhau trên thế giới.',
    vocabulary: ['cafeteria (n): quán ăn tự phục vụ', 'dish (n): món ăn', 'region (n): vùng, miền'],
  },
  {
    questionNo: 105,
    part: 5,
    question: "Ms. Patel is coming to Delhi today to visit possible _____ for her company's new warehouse.",
    options: [
      { letter: 'A', text: 'locating' },
      { letter: 'B', text: 'locations' },
      { letter: 'C', text: 'located' },
      { letter: 'D', text: 'locate' },
    ],
    answer: 'B',
    explanation: 'Sau ngoại động từ "visit" cần một danh từ làm tân ngữ. Trước chỗ trống có tính từ "possible", càng xác nhận cần danh từ phía sau. "Locations" là danh từ số nhiều nghĩa là các địa điểm. Các đáp án còn lại là dạng động từ/phân từ.',
    translation: 'Cô Patel hôm nay sẽ đến Delhi để xem các địa điểm khả thi cho nhà kho mới của công ty.',
    vocabulary: ['location (n): địa điểm', 'warehouse (n): nhà kho', 'locate (v): xác định vị trí'],
  },
  {
    questionNo: 106,
    part: 5,
    question: 'Clydeway, Inc., has grown dramatically _____ its beginnings as a small corner grocery store.',
    options: [
      { letter: 'A', text: 'since' },
      { letter: 'B', text: 'such' },
      { letter: 'C', text: 'except' },
      { letter: 'D', text: 'however' },
    ],
    answer: 'A',
    explanation: 'Câu dùng hiện tại hoàn thành "has grown", và phía sau là mốc bắt đầu "its beginnings...". "Since" là giới từ/liên từ chỉ từ một thời điểm trong quá khứ đến hiện tại, rất hợp với hiện tại hoàn thành. Các đáp án còn lại không diễn tả mốc thời gian bắt đầu.',
    translation: 'Clydeway, Inc. đã phát triển đáng kể kể từ khởi đầu là một cửa hàng tạp hóa nhỏ ở góc phố.',
    vocabulary: ['dramatically (adv): đáng kể, mạnh mẽ', 'grocery store (n): cửa hàng tạp hóa', 'beginning (n): sự khởi đầu'],
  },
  {
    questionNo: 107,
    part: 5,
    question: "When booking a flight, it is wise to _____ the guidelines for luggage size on the airline's Web site.",
    options: [
      { letter: 'A', text: 'check' },
      { letter: 'B', text: 'close' },
      { letter: 'C', text: 'approve' },
      { letter: 'D', text: 'list' },
    ],
    answer: 'A',
    explanation: 'Sau "it is wise to" cần động từ nguyên mẫu. Về nghĩa, khi đặt vé máy bay thì nên "check the guidelines" là kiểm tra hướng dẫn/quy định. Các động từ còn lại không hợp với ngữ cảnh xem quy định kích thước hành lý.',
    translation: 'Khi đặt vé máy bay, bạn nên kiểm tra hướng dẫn về kích thước hành lý trên trang web của hãng hàng không.',
    vocabulary: ['book a flight: đặt chuyến bay', 'guideline (n): hướng dẫn, quy định', 'luggage (n): hành lý'],
  },
  {
    questionNo: 108,
    part: 5,
    question: 'The melody is so _____ that the composer has simplified parts of it for live performances.',
    options: [
      { letter: 'A', text: 'direct' },
      { letter: 'B', text: 'complex' },
      { letter: 'C', text: 'favorable' },
      { letter: 'D', text: 'helpful' },
    ],
    answer: 'B',
    explanation: 'Cấu trúc "so + adjective + that" diễn tả quá ... đến nỗi .... Phần sau nói nhà soạn nhạc đã đơn giản hóa một số đoạn để biểu diễn trực tiếp, nên tính từ hợp nghĩa là "complex" (phức tạp).',
    translation: 'Giai điệu phức tạp đến nỗi nhà soạn nhạc đã đơn giản hóa một số phần để biểu diễn trực tiếp.',
    vocabulary: ['melody (n): giai điệu', 'composer (n): nhà soạn nhạc', 'simplify (v): đơn giản hóa'],
  },
  {
    questionNo: 109,
    part: 5,
    question: "The test group found the illustrations in the appliance users' guide to be highly _____.",
    options: [
      { letter: 'A', text: 'inform' },
      { letter: 'B', text: 'information' },
      { letter: 'C', text: 'informatively' },
      { letter: 'D', text: 'informative' },
    ],
    answer: 'D',
    explanation: 'Cấu trúc là "find + object + to be + adjective": nhận thấy cái gì có tính chất gì. Trạng từ "highly" cũng bổ nghĩa cho tính từ. "Informative" là tính từ nghĩa là giàu thông tin/hữu ích. "Inform" là động từ, "information" là danh từ, "informatively" là trạng từ.',
    translation: 'Nhóm thử nghiệm nhận thấy các hình minh họa trong hướng dẫn sử dụng thiết bị rất giàu thông tin.',
    vocabulary: ['illustration (n): hình minh họa', 'appliance (n): thiết bị', 'informative (adj): cung cấp nhiều thông tin'],
  },
  {
    questionNo: 110,
    part: 5,
    question: "The directions for Masuda's do-it-yourself projects are comprehensive enough for _____ a novice builder.",
    options: [
      { letter: 'A', text: 'right' },
      { letter: 'B', text: 'soon' },
      { letter: 'C', text: 'how' },
      { letter: 'D', text: 'even' },
    ],
    answer: 'D',
    explanation: 'Câu muốn nhấn mạnh rằng hướng dẫn đủ chi tiết cho cả người mới làm xây dựng. "Even" nghĩa là thậm chí, dùng để nhấn mạnh đối tượng bất ngờ hoặc mức độ cao. Các đáp án còn lại không hợp nghĩa trước cụm danh từ "a novice builder".',
    translation: 'Các hướng dẫn cho dự án tự làm của Masuda đủ toàn diện để ngay cả người mới xây dựng cũng làm theo được.',
    vocabulary: ['direction (n): hướng dẫn', 'comprehensive (adj): toàn diện, chi tiết', 'novice (n): người mới'],
  },
  {
    questionNo: 111,
    part: 5,
    question: '_____ of the two candidates for the position had the necessary qualifications.',
    options: [
      { letter: 'A', text: 'Neither' },
      { letter: 'B', text: 'Nobody' },
      { letter: 'C', text: 'None' },
      { letter: 'D', text: 'Nothing' },
    ],
    answer: 'A',
    explanation: 'Câu nói về "the two candidates" là hai ứng viên. Khi phủ định cả hai trong hai đối tượng, dùng "neither of". "None of" thường dùng cho ba đối tượng trở lên hoặc số lượng không xác định, "nobody/nothing" không đi với "of the two candidates" theo cấu trúc này.',
    translation: 'Cả hai ứng viên cho vị trí đó đều không có các bằng cấp/năng lực cần thiết.',
    vocabulary: ['candidate (n): ứng viên', 'qualification (n): năng lực, bằng cấp', 'neither of: không ai/cái nào trong hai'],
  },
  {
    questionNo: 112,
    part: 5,
    question: 'The need for highly trained electricians in the construction _____ has grown rapidly in recent years.',
    options: [
      { letter: 'A', text: 'employment' },
      { letter: 'B', text: 'activity' },
      { letter: 'C', text: 'knowledge' },
      { letter: 'D', text: 'industry' },
    ],
    answer: 'D',
    explanation: 'Cụm tự nhiên là "construction industry", nghĩa là ngành xây dựng. Câu nói về nhu cầu thợ điện được đào tạo trong một lĩnh vực/ngành, nên "industry" phù hợp nhất về nghĩa.',
    translation: 'Nhu cầu về thợ điện được đào tạo chuyên sâu trong ngành xây dựng đã tăng nhanh trong những năm gần đây.',
    vocabulary: ['electrician (n): thợ điện', 'construction industry (n): ngành xây dựng', 'rapidly (adv): nhanh chóng'],
  },
  {
    questionNo: 113,
    part: 5,
    question: 'Ms. Daly will prepare a marketing budget and propose _____ during the client meeting.',
    options: [
      { letter: 'A', text: 'those' },
      { letter: 'B', text: 'its' },
      { letter: 'C', text: 'it' },
      { letter: 'D', text: 'her' },
    ],
    answer: 'C',
    explanation: 'Đại từ cần thay thế cho cụm danh từ số ít "a marketing budget". Đại từ tân ngữ phù hợp là "it". "Those" thay cho danh từ số nhiều, "its" là tính từ/đại từ sở hữu, "her" không thay cho vật.',
    translation: 'Cô Daly sẽ chuẩn bị ngân sách tiếp thị và đề xuất nó trong cuộc họp với khách hàng.',
    vocabulary: ['marketing budget (n): ngân sách tiếp thị', 'propose (v): đề xuất', 'client meeting (n): cuộc họp với khách hàng'],
  },
  {
    questionNo: 114,
    part: 5,
    question: 'Mr. Silva asked sales staff to _____ travel expenditures to help cut costs.',
    options: [
      { letter: 'A', text: 'convince' },
      { letter: 'B', text: 'require' },
      { letter: 'C', text: 'decide' },
      { letter: 'D', text: 'limit' },
    ],
    answer: 'D',
    explanation: 'Cấu trúc "ask someone to V" cần động từ nguyên mẫu. Về nghĩa, để cắt giảm chi phí thì nhân viên cần "limit travel expenditures" là hạn chế chi tiêu đi lại. Các động từ còn lại không hợp với tân ngữ "travel expenditures".',
    translation: 'Ông Silva yêu cầu nhân viên bán hàng hạn chế chi tiêu đi lại để giúp cắt giảm chi phí.',
    vocabulary: ['sales staff (n): nhân viên bán hàng', 'expenditure (n): khoản chi tiêu', 'cut costs: cắt giảm chi phí'],
  },
  {
    questionNo: 115,
    part: 5,
    question: 'The city council will discuss certain policies, particularly those made _____ the previous administration.',
    options: [
      { letter: 'A', text: 'any' },
      { letter: 'B', text: 'by' },
      { letter: 'C', text: 'to' },
      { letter: 'D', text: 'and' },
    ],
    answer: 'B',
    explanation: '"Those" thay cho "policies". Cụm "made by the previous administration" là rút gọn mệnh đề quan hệ bị động: policies that were made by.... Sau phân từ bị động "made", giới từ "by" chỉ tác nhân tạo ra chính sách.',
    translation: 'Hội đồng thành phố sẽ thảo luận một số chính sách, đặc biệt là những chính sách do chính quyền trước ban hành.',
    vocabulary: ['city council (n): hội đồng thành phố', 'policy (n): chính sách', 'administration (n): chính quyền, ban quản trị'],
  },
  {
    questionNo: 116,
    part: 5,
    question: "Servers' tips are pooled at the end of each shift and divided evenly _____ the entire waitstaff.",
    options: [
      { letter: 'A', text: 'onto' },
      { letter: 'B', text: 'among' },
      { letter: 'C', text: 'beside' },
      { letter: 'D', text: 'about' },
    ],
    answer: 'B',
    explanation: 'Khi chia một khoản gì cho các thành viên trong một nhóm, dùng "among". Cụm "divided evenly among the entire waitstaff" nghĩa là được chia đều cho toàn bộ nhân viên phục vụ.',
    translation: 'Tiền boa của phục vụ được gộp lại cuối mỗi ca và chia đều cho toàn bộ nhân viên phục vụ.',
    vocabulary: ['tip (n): tiền boa', 'pool (v): gộp chung', 'waitstaff (n): đội ngũ phục vụ'],
  },
  {
    questionNo: 117,
    part: 5,
    question: 'Costpa Analytics Ltd. has made successful _____ in two emerging data companies.',
    options: [
      { letter: 'A', text: 'investments' },
      { letter: 'B', text: 'invested' },
      { letter: 'C', text: 'invest' },
      { letter: 'D', text: 'investor' },
    ],
    answer: 'A',
    explanation: 'Sau động từ "made" và tính từ "successful" cần một danh từ làm tân ngữ. Cụm đúng là "make investments in..." nghĩa là đầu tư vào. "Investor" là nhà đầu tư, không hợp nghĩa với "made successful"; các đáp án B/C là động từ.',
    translation: 'Costpa Analytics Ltd. đã thực hiện các khoản đầu tư thành công vào hai công ty dữ liệu mới nổi.',
    vocabulary: ['investment (n): khoản đầu tư', 'emerging (adj): mới nổi', 'data company (n): công ty dữ liệu'],
  },
  {
    questionNo: 118,
    part: 5,
    question: "Vallentrade manages clients' accounts more _____ than most other brokerage firms.",
    options: [
      { letter: 'A', text: 'conserves' },
      { letter: 'B', text: 'conservative' },
      { letter: 'C', text: 'conservatively' },
      { letter: 'D', text: 'conserving' },
    ],
    answer: 'C',
    explanation: 'Chỗ trống bổ nghĩa cho động từ "manages", nên cần trạng từ. Cấu trúc so sánh hơn với trạng từ dài là "more + adverb + than". "Conservatively" là trạng từ nghĩa là thận trọng/bảo thủ. "Conservative" là tính từ, còn các đáp án A/D là dạng động từ.',
    translation: 'Vallentrade quản lý tài khoản của khách hàng thận trọng hơn hầu hết các công ty môi giới khác.',
    vocabulary: ['manage (v): quản lý', 'account (n): tài khoản', 'brokerage firm (n): công ty môi giới'],
  },
  {
    questionNo: 119,
    part: 5,
    question: 'The ideal operating temperature for the tablet computer is _____ 10 and 30 degrees Celsius.',
    options: [
      { letter: 'A', text: 'between' },
      { letter: 'B', text: 'above' },
      { letter: 'C', text: 'in' },
      { letter: 'D', text: 'off' },
    ],
    answer: 'A',
    explanation: 'Cấu trúc đúng là "between A and B": nằm giữa A và B. Ở đây là khoảng nhiệt độ từ 10 đến 30 độ C. Các giới từ còn lại không đi với cặp "10 and 30".',
    translation: 'Nhiệt độ hoạt động lý tưởng cho máy tính bảng là từ 10 đến 30 độ C.',
    vocabulary: ['operating temperature (n): nhiệt độ hoạt động', 'tablet computer (n): máy tính bảng', 'degree Celsius: độ C'],
  },
  {
    questionNo: 120,
    part: 5,
    question: 'Of the people who have publicly introduced _____ at the Carpentry Club meetings, about half are commercial contractors.',
    options: [
      { letter: 'A', text: 'their' },
      { letter: 'B', text: 'their own' },
      { letter: 'C', text: 'they' },
      { letter: 'D', text: 'themselves' },
    ],
    answer: 'D',
    explanation: 'Động từ "introduce" cần tân ngữ. Khi chủ thể tự giới thiệu chính họ, dùng đại từ phản thân "themselves". "Their/their own" cần danh từ phía sau, còn "they" là đại từ chủ ngữ.',
    translation: 'Trong số những người đã tự giới thiệu công khai tại các cuộc họp của Câu lạc bộ Carpentry, khoảng một nửa là nhà thầu thương mại.',
    vocabulary: ['publicly (adv): công khai', 'introduce oneself: tự giới thiệu', 'contractor (n): nhà thầu'],
  },
  {
    questionNo: 121,
    part: 5,
    question: 'On Thursday, the technician will be on Sratus Road _____ two gas stoves.',
    options: [
      { letter: 'A', text: 'serviced' },
      { letter: 'B', text: 'service' },
      { letter: 'C', text: 'to service' },
      { letter: 'D', text: 'is servicing' },
    ],
    answer: 'C',
    explanation: 'Câu đã có vị ngữ "will be on Sratus Road". Phần sau cần cụm chỉ mục đích: có mặt trên đường Sratus để làm gì. Dùng "to + V" chỉ mục đích: "to service two gas stoves".',
    translation: 'Vào thứ Năm, kỹ thuật viên sẽ có mặt trên đường Sratus để bảo dưỡng hai bếp gas.',
    vocabulary: ['technician (n): kỹ thuật viên', 'service (v): bảo dưỡng', 'gas stove (n): bếp gas'],
  },
  {
    questionNo: 122,
    part: 5,
    question: 'The spreadsheet _____ data on retail sales during the fourth quarter is attached.',
    options: [
      { letter: 'A', text: 'contains' },
      { letter: 'B', text: 'contained' },
      { letter: 'C', text: 'containing' },
      { letter: 'D', text: 'containable' },
    ],
    answer: 'C',
    explanation: 'Câu đã có động từ chính "is attached", nên chỗ trống không thể là động từ chia thì "contains". Đây là rút gọn mệnh đề quan hệ chủ động: "The spreadsheet which contains data..." thành "The spreadsheet containing data...".',
    translation: 'Bảng tính chứa dữ liệu về doanh số bán lẻ trong quý 4 được đính kèm.',
    vocabulary: ['spreadsheet (n): bảng tính', 'retail sales (n): doanh số bán lẻ', 'fourth quarter (n): quý 4'],
  },
  {
    questionNo: 123,
    part: 5,
    question: 'See our weekly promotional flyer for complete _____ of the discounted items.',
    options: [
      { letter: 'A', text: 'exchange' },
      { letter: 'B', text: 'support' },
      { letter: 'C', text: 'receipts' },
      { letter: 'D', text: 'descriptions' },
    ],
    answer: 'D',
    explanation: 'Cụm "complete descriptions of the discounted items" nghĩa là mô tả đầy đủ về các mặt hàng giảm giá. Về nghĩa, tờ rơi khuyến mãi cung cấp mô tả sản phẩm, không phải trao đổi, hỗ trợ hay biên lai.',
    translation: 'Hãy xem tờ rơi khuyến mãi hàng tuần của chúng tôi để biết mô tả đầy đủ về các mặt hàng được giảm giá.',
    vocabulary: ['promotional flyer (n): tờ rơi khuyến mãi', 'description (n): mô tả', 'discounted item (n): mặt hàng được giảm giá'],
  },
  {
    questionNo: 124,
    part: 5,
    question: 'New salespeople are instructed to research the businesses of _____ customers before contacting them for the first time.',
    options: [
      { letter: 'A', text: 'total' },
      { letter: 'B', text: 'potential' },
      { letter: 'C', text: 'equal' },
      { letter: 'D', text: 'factual' },
    ],
    answer: 'B',
    explanation: 'Chỗ trống bổ nghĩa cho danh từ "customers". Về nghĩa, nhân viên bán hàng mới cần tìm hiểu doanh nghiệp của "potential customers" là khách hàng tiềm năng trước khi liên hệ lần đầu.',
    translation: 'Nhân viên bán hàng mới được hướng dẫn tìm hiểu doanh nghiệp của khách hàng tiềm năng trước khi liên hệ lần đầu.',
    vocabulary: ['salespeople (n): nhân viên bán hàng', 'potential customer (n): khách hàng tiềm năng', 'contact (v): liên hệ'],
  },
  {
    questionNo: 125,
    part: 5,
    question: 'If you use online banking, bills can be paid _____ it is most convenient.',
    options: [
      { letter: 'A', text: 'whenever' },
      { letter: 'B', text: 'simply' },
      { letter: 'C', text: 'accordingly' },
      { letter: 'D', text: 'quite' },
    ],
    answer: 'A',
    explanation: 'Sau chỗ trống là một mệnh đề "it is most convenient". "Whenever" nối mệnh đề thời gian, nghĩa là bất cứ khi nào. Câu muốn nói hóa đơn có thể được thanh toán bất cứ khi nào thuận tiện nhất.',
    translation: 'Nếu bạn dùng ngân hàng trực tuyến, hóa đơn có thể được thanh toán bất cứ khi nào thuận tiện nhất.',
    vocabulary: ['online banking (n): ngân hàng trực tuyến', 'bill (n): hóa đơn', 'convenient (adj): thuận tiện'],
  },
  {
    questionNo: 126,
    part: 5,
    question: 'Our internship combines lectures with real-world projects to provide formal instruction _____ professional experience.',
    options: [
      { letter: 'A', text: 'above all' },
      { letter: 'B', text: 'as well as' },
      { letter: 'C', text: 'now that' },
      { letter: 'D', text: 'in order to' },
    ],
    answer: 'B',
    explanation: 'Câu liệt kê hai thứ mà chương trình thực tập cung cấp: formal instruction và professional experience. "As well as" nghĩa là cũng như, dùng để nối hai thành phần song song. "In order to" phải đi với động từ nguyên mẫu, không đi với cụm danh từ ở đây.',
    translation: 'Chương trình thực tập của chúng tôi kết hợp bài giảng với dự án thực tế để cung cấp hướng dẫn chính thức cũng như kinh nghiệm chuyên môn.',
    vocabulary: ['internship (n): kỳ thực tập', 'lecture (n): bài giảng', 'professional experience (n): kinh nghiệm chuyên môn'],
  },
  {
    questionNo: 127,
    part: 5,
    question: 'Employee _____ at Medmile Ventures include share options and scheduled raises.',
    options: [
      { letter: 'A', text: 'beneficial' },
      { letter: 'B', text: 'beneficially' },
      { letter: 'C', text: 'benefits' },
      { letter: 'D', text: 'benefited' },
    ],
    answer: 'C',
    explanation: 'Chỗ trống là danh từ chính trong cụm chủ ngữ "Employee _____ at Medmile Ventures". Động từ "include" ở dạng số nhiều, nên chủ ngữ phải là danh từ số nhiều. "Employee benefits" là cụm danh từ nghĩa là phúc lợi nhân viên.',
    translation: 'Phúc lợi nhân viên tại Medmile Ventures bao gồm quyền chọn cổ phiếu và các đợt tăng lương theo lịch.',
    vocabulary: ['employee benefits (n): phúc lợi nhân viên', 'share options (n): quyền chọn cổ phiếu', 'raise (n): tăng lương'],
  },
  {
    questionNo: 128,
    part: 5,
    question: 'City _____ hope to get the necessary permits to build a twenty-story office building on Minerva Street.',
    options: [
      { letter: 'A', text: 'agendas' },
      { letter: 'B', text: 'developers' },
      { letter: 'C', text: 'avenues' },
      { letter: 'D', text: 'boundaries' },
    ],
    answer: 'B',
    explanation: 'Chủ ngữ phải là người/nhóm người có thể hy vọng xin giấy phép xây tòa nhà. "City developers" là các nhà phát triển đô thị. Các danh từ còn lại như agenda, avenue, boundary không phải chủ thể phù hợp để xin giấy phép xây dựng.',
    translation: 'Các nhà phát triển đô thị hy vọng nhận được giấy phép cần thiết để xây một tòa nhà văn phòng hai mươi tầng trên phố Minerva.',
    vocabulary: ['developer (n): nhà phát triển', 'permit (n): giấy phép', 'twenty-story (adj): hai mươi tầng'],
  },
  {
    questionNo: 129,
    part: 5,
    question: 'Compliance Department officers regularly monitor changes in the _____ framework.',
    options: [
      { letter: 'A', text: 'regulate' },
      { letter: 'B', text: 'regulates' },
      { letter: 'C', text: 'regulator' },
      { letter: 'D', text: 'regulatory' },
    ],
    answer: 'D',
    explanation: 'Chỗ trống đứng trước danh từ "framework", nên cần tính từ bổ nghĩa cho danh từ. "Regulatory framework" là cụm cố định nghĩa là khung pháp lý/khuôn khổ quy định. "Regulate/regulates" là động từ, "regulator" là danh từ chỉ cơ quan/người điều tiết.',
    translation: 'Các nhân viên Bộ phận Tuân thủ thường xuyên theo dõi những thay đổi trong khung pháp lý.',
    vocabulary: ['compliance (n): tuân thủ', 'monitor (v): theo dõi', 'regulatory framework (n): khung pháp lý'],
  },
  {
    questionNo: 130,
    part: 5,
    question: 'The X250 portable heater achieves the desirable _____ without reaching especially high temperatures.',
    options: [
      { letter: 'A', text: 'practices' },
      { letter: 'B', text: 'factors' },
      { letter: 'C', text: 'outcomes' },
      { letter: 'D', text: 'dimensions' },
    ],
    answer: 'C',
    explanation: 'Cụm "achieve the desirable outcomes" nghĩa là đạt được các kết quả mong muốn. Ngữ cảnh nói máy sưởi đạt hiệu quả mong muốn mà không cần nhiệt độ quá cao. Các danh từ còn lại không hợp với động từ "achieves" trong câu này.',
    translation: 'Máy sưởi di động X250 đạt được kết quả mong muốn mà không cần đạt đến nhiệt độ quá cao.',
    vocabulary: ['portable heater (n): máy sưởi di động', 'desirable (adj): mong muốn', 'outcome (n): kết quả'],
  },
];

export const PART5_2022_TEST_4_SET: PracticeQuestion[] = [
  {
    questionNo: 101,
    part: 5,
    question: 'Mr. Akagi was unable to buy tickets for the concert because _____ was sold out.',
    options: [
      { letter: 'A', text: 'it' },
      { letter: 'B', text: 'others' },
      { letter: 'C', text: 'any' },
      { letter: 'D', text: 'they' },
    ],
    answer: 'A',
    explanation: 'Vế sau dùng động từ "was", nên chủ ngữ phải là số ít. "It" thay cho sự kiện/buổi hòa nhạc hoặc tình huống vé đã hết. Nếu chủ ngữ là "tickets" số nhiều thì động từ phải là "were", khi đó mới có thể dùng "they".',
    translation: 'Ông Akagi đã không thể mua vé cho buổi hòa nhạc vì nó đã được bán hết.',
    vocabulary: ['concert (n): buổi hòa nhạc', 'sold out: bán hết', 'ticket (n): vé'],
  },
  {
    questionNo: 102,
    part: 5,
    question: 'Classes _____ using the new employee scheduling software will begin in December.',
    options: [
      { letter: 'A', text: 'at' },
      { letter: 'B', text: 'to' },
      { letter: 'C', text: 'by' },
      { letter: 'D', text: 'on' },
    ],
    answer: 'D',
    explanation: 'Cần giới từ diễn tả chủ đề/nội dung của lớp học. "Classes on using..." nghĩa là các lớp học về cách sử dụng phần mềm. "At", "to", "by" không diễn tả đúng quan hệ nội dung bài học trong câu này.',
    translation: 'Các lớp học về cách sử dụng phần mềm lên lịch nhân viên mới sẽ bắt đầu vào tháng 12.',
    vocabulary: ['employee (n): nhân viên', 'scheduling software (n): phần mềm lên lịch', 'class on: lớp học về'],
  },
  {
    questionNo: 103,
    part: 5,
    question: "Hillsdale Fabrics' _____ collection of leathers was imported from Italy.",
    options: [
      { letter: 'A', text: 'diversity' },
      { letter: 'B', text: 'diversely' },
      { letter: 'C', text: 'diversify' },
      { letter: 'D', text: 'diverse' },
    ],
    answer: 'D',
    explanation: 'Chỗ trống đứng trước danh từ "collection", nên cần tính từ để bổ nghĩa cho danh từ. "Diverse" là tính từ nghĩa là đa dạng. "Diversity" là danh từ, "diversely" là trạng từ, "diversify" là động từ.',
    translation: 'Bộ sưu tập da đa dạng của Hillsdale Fabrics được nhập khẩu từ Ý.',
    vocabulary: ['diverse (adj): đa dạng', 'collection (n): bộ sưu tập', 'import (v): nhập khẩu'],
  },
  {
    questionNo: 104,
    part: 5,
    question: 'A _____ of four dental hygienists spoke about careers in their field.',
    options: [
      { letter: 'A', text: 'plan' },
      { letter: 'B', text: 'panel' },
      { letter: 'C', text: 'support' },
      { letter: 'D', text: 'version' },
    ],
    answer: 'B',
    explanation: 'Cụm "a panel of..." nghĩa là một nhóm/hội đồng gồm những người được mời thảo luận hoặc trình bày. Vì phía sau là bốn chuyên viên nha khoa cùng nói về nghề nghiệp, "panel" là danh từ phù hợp nhất.',
    translation: 'Một hội đồng gồm bốn chuyên viên nha khoa đã nói về nghề nghiệp trong lĩnh vực của họ.',
    vocabulary: ['panel (n): hội đồng, nhóm thảo luận', 'dental (adj): nha khoa', 'field (n): lĩnh vực'],
  },
  {
    questionNo: 105,
    part: 5,
    question: 'Ardentine Realty is _____ seeking new rental properties for its portfolio.',
    options: [
      { letter: 'A', text: 'actively' },
      { letter: 'B', text: 'activate' },
      { letter: 'C', text: 'activity' },
      { letter: 'D', text: 'active' },
    ],
    answer: 'A',
    explanation: 'Câu dùng hiện tại tiếp diễn "is seeking"; chỗ trống cần trạng từ bổ nghĩa cho động từ "seeking". "Actively" nghĩa là một cách tích cực/chủ động. "Active" là tính từ, "activity" là danh từ, "activate" là động từ.',
    translation: 'Ardentine Realty đang tích cực tìm kiếm các bất động sản cho thuê mới cho danh mục đầu tư của mình.',
    vocabulary: ['realty (n): bất động sản', 'rental property (n): bất động sản cho thuê', 'portfolio (n): danh mục đầu tư'],
  },
  {
    questionNo: 106,
    part: 5,
    question: 'This Friday, Zone Fly Cameras invites the public to a free aerial photography _____.',
    options: [
      { letter: 'A', text: 'picture' },
      { letter: 'B', text: 'ticket' },
      { letter: 'C', text: 'action' },
      { letter: 'D', text: 'workshop' },
    ],
    answer: 'D',
    explanation: 'Câu nói công ty mời công chúng tham gia một sự kiện miễn phí về chụp ảnh từ trên không. "Workshop" nghĩa là hội thảo/lớp thực hành, hợp với hành động "invites the public to". Các danh từ còn lại không hợp ngữ cảnh.',
    translation: 'Thứ Sáu này, Zone Fly Cameras mời công chúng tham dự một hội thảo chụp ảnh từ trên không miễn phí.',
    vocabulary: ['aerial (adj): trên không', 'photography (n): nhiếp ảnh', 'workshop (n): hội thảo, buổi thực hành'],
  },
  {
    questionNo: 107,
    part: 5,
    question: 'The Ambury Prize recognizes research that is notable for its _____ and innovation.',
    options: [
      { letter: 'A', text: 'creative' },
      { letter: 'B', text: 'creatively' },
      { letter: 'C', text: 'creativity' },
      { letter: 'D', text: 'creates' },
    ],
    answer: 'C',
    explanation: 'Cấu trúc song song "A and B": từ cần điền phải cùng loại với "innovation", là danh từ. "Creativity" là danh từ nghĩa là sự sáng tạo. "Creative" là tính từ, "creatively" là trạng từ, "creates" là động từ.',
    translation: 'Giải thưởng Ambury công nhận nghiên cứu nổi bật vì sự sáng tạo và đổi mới của nó.',
    vocabulary: ['recognize (v): công nhận', 'notable (adj): đáng chú ý', 'innovation (n): sự đổi mới'],
  },
  {
    questionNo: 108,
    part: 5,
    question: 'This year the harvest parade will _____ the village, beginning and ending at the town square.',
    options: [
      { letter: 'A', text: 'spin' },
      { letter: 'B', text: 'circle' },
      { letter: 'C', text: 'roll' },
      { letter: 'D', text: 'loosen' },
    ],
    answer: 'B',
    explanation: 'Động từ "circle" nghĩa là đi vòng quanh. Ngữ cảnh cuộc diễu hành bắt đầu và kết thúc ở quảng trường, tức là di chuyển quanh làng. Các động từ còn lại không hợp với tân ngữ "the village" trong nghĩa này.',
    translation: 'Năm nay cuộc diễu hành mùa thu hoạch sẽ đi vòng quanh ngôi làng, bắt đầu và kết thúc tại quảng trường thị trấn.',
    vocabulary: ['harvest (n): mùa thu hoạch', 'parade (n): cuộc diễu hành', 'town square (n): quảng trường thị trấn'],
  },
  {
    questionNo: 109,
    part: 5,
    question: "Questwiz, the library's newest database, _____ a wide range of resource materials.",
    options: [
      { letter: 'A', text: 'to contain' },
      { letter: 'B', text: 'contains' },
      { letter: 'C', text: 'container' },
      { letter: 'D', text: 'containing' },
    ],
    answer: 'B',
    explanation: 'Chủ ngữ chính là "Questwiz", cụm "the library\'s newest database" chỉ là phần bổ nghĩa chen giữa hai dấu phẩy. Câu cần động từ chính chia theo chủ ngữ số ít, nên chọn "contains".',
    translation: 'Questwiz, cơ sở dữ liệu mới nhất của thư viện, chứa nhiều loại tài liệu nguồn.',
    vocabulary: ['database (n): cơ sở dữ liệu', 'contain (v): chứa, bao gồm', 'resource material (n): tài liệu nguồn'],
  },
  {
    questionNo: 110,
    part: 5,
    question: 'After more than three years, the application for the new patent was _____ approved.',
    options: [
      { letter: 'A', text: 'already' },
      { letter: 'B', text: 'finally' },
      { letter: 'C', text: 'constantly' },
      { letter: 'D', text: 'exactly' },
    ],
    answer: 'B',
    explanation: 'Cụm "After more than three years" cho thấy kết quả đạt được sau một thời gian dài chờ đợi. Trạng từ phù hợp là "finally" nghĩa là cuối cùng. Các trạng từ còn lại không nhấn mạnh quá trình kéo dài rồi có kết quả.',
    translation: 'Sau hơn ba năm, đơn xin cấp bằng sáng chế mới cuối cùng đã được chấp thuận.',
    vocabulary: ['patent (n): bằng sáng chế', 'application (n): đơn xin', 'approve (v): chấp thuận'],
  },
  {
    questionNo: 111,
    part: 5,
    question: 'The First Street Hotel has almost always been fully booked since it _____ last year.',
    options: [
      { letter: 'A', text: 'had renovated' },
      { letter: 'B', text: 'renovated' },
      { letter: 'C', text: 'was renovating' },
      { letter: 'D', text: 'was renovated' },
    ],
    answer: 'D',
    explanation: '"It" thay cho "The First Street Hotel". Khách sạn không tự cải tạo chính nó, mà được cải tạo, nên cần bị động quá khứ đơn: "was renovated". Mốc "last year" cũng phù hợp với quá khứ đơn.',
    translation: 'Khách sạn First Street hầu như luôn được đặt kín chỗ kể từ khi nó được cải tạo vào năm ngoái.',
    vocabulary: ['renovate (v): cải tạo, tân trang', 'fully booked: được đặt kín chỗ'],
  },
  {
    questionNo: 112,
    part: 5,
    question: 'Departments should not spend an _____ amount of their budgets on office supplies.',
    options: [
      { letter: 'A', text: 'equal' },
      { letter: 'B', text: 'exciting' },
      { letter: 'C', text: 'excessive' },
      { letter: 'D', text: 'unknown' },
    ],
    answer: 'C',
    explanation: 'Cụm "an excessive amount of..." nghĩa là một lượng quá mức. Ngữ cảnh nói các phòng ban không nên chi quá nhiều ngân sách cho văn phòng phẩm, nên "excessive" là tính từ phù hợp nhất.',
    translation: 'Các phòng ban không nên chi một lượng quá mức ngân sách của họ cho văn phòng phẩm.',
    vocabulary: ['department (n): phòng ban', 'budget (n): ngân sách', 'office supplies (n): văn phòng phẩm'],
  },
  {
    questionNo: 113,
    part: 5,
    question: 'Maxwell Copies prints brochures on thick, glossy paper that was _____ selected for its quality and durability.',
    options: [
      { letter: 'A', text: 'caring' },
      { letter: 'B', text: 'careful' },
      { letter: 'C', text: 'carefully' },
      { letter: 'D', text: 'cares' },
    ],
    answer: 'C',
    explanation: 'Chỗ trống đứng trước động từ phân từ "selected" trong cấu trúc bị động "was selected", nên cần trạng từ bổ nghĩa cho hành động chọn. "Carefully selected" nghĩa là được lựa chọn cẩn thận.',
    translation: 'Maxwell Copies in tài liệu quảng cáo trên giấy dày, bóng được lựa chọn cẩn thận vì chất lượng và độ bền.',
    vocabulary: ['brochure (n): tài liệu quảng cáo', 'glossy (adj): bóng', 'durability (n): độ bền'],
  },
  {
    questionNo: 114,
    part: 5,
    question: '_____ Mr. Kamau has worked for Mombasa Communications for two years, he has never taken time off.',
    options: [
      { letter: 'A', text: 'Although' },
      { letter: 'B', text: 'But' },
      { letter: 'C', text: 'Neither' },
      { letter: 'D', text: 'Yet' },
    ],
    answer: 'A',
    explanation: 'Hai mệnh đề có ý tương phản: dù đã làm việc hai năm nhưng chưa từng nghỉ phép. Để mở đầu mệnh đề phụ chỉ nhượng bộ, dùng "Although". "But" thường nối hai mệnh đề độc lập và không đứng cùng vị trí này với dấu phẩy như vậy.',
    translation: 'Mặc dù ông Kamau đã làm việc cho Mombasa Communications được hai năm, ông ấy chưa bao giờ nghỉ phép.',
    vocabulary: ['time off (n): thời gian nghỉ phép', 'although: mặc dù'],
  },
  {
    questionNo: 115,
    part: 5,
    question: 'At the Morrighan Hotel, addressing customer feedback is of _____ importance.',
    options: [
      { letter: 'A', text: 'critique' },
      { letter: 'B', text: 'critic' },
      { letter: 'C', text: 'critically' },
      { letter: 'D', text: 'critical' },
    ],
    answer: 'D',
    explanation: 'Chỗ trống đứng trước danh từ "importance", nên cần tính từ bổ nghĩa cho danh từ. "Of critical importance" là cụm nghĩa là vô cùng quan trọng. "Critically" là trạng từ, "critic/critique" là danh từ/động từ.',
    translation: 'Tại khách sạn Morrighan, việc xử lý phản hồi của khách hàng là vô cùng quan trọng.',
    vocabulary: ['address (v): xử lý, giải quyết', 'feedback (n): phản hồi', 'critical importance: tầm quan trọng thiết yếu'],
  },
  {
    questionNo: 116,
    part: 5,
    question: "Axofare's new computer program enables users to _____ organize and retrieve data.",
    options: [
      { letter: 'A', text: 'efficiently' },
      { letter: 'B', text: 'irreversibly' },
      { letter: 'C', text: 'vaguely' },
      { letter: 'D', text: 'especially' },
    ],
    answer: 'A',
    explanation: 'Chỗ trống đứng trước hai động từ "organize and retrieve", nên cần trạng từ bổ nghĩa cho cách thực hiện. Về nghĩa, phần mềm giúp người dùng sắp xếp và truy xuất dữ liệu "efficiently" là một cách hiệu quả.',
    translation: 'Chương trình máy tính mới của Axofare cho phép người dùng sắp xếp và truy xuất dữ liệu một cách hiệu quả.',
    vocabulary: ['enable (v): cho phép', 'organize (v): sắp xếp', 'retrieve (v): truy xuất, lấy lại'],
  },
  {
    questionNo: 117,
    part: 5,
    question: 'Trelmoni Corporation has just released its _____ of the global stock market.',
    options: [
      { letter: 'A', text: 'analysis' },
      { letter: 'B', text: 'analytical' },
      { letter: 'C', text: 'analyze' },
      { letter: 'D', text: 'analyzed' },
    ],
    answer: 'A',
    explanation: 'Sau tính từ sở hữu "its" và trước "of the global stock market" cần một danh từ chính. "Analysis" là danh từ nghĩa là bản phân tích. "Analytical" là tính từ, "analyze" là động từ, "analyzed" là phân từ.',
    translation: 'Trelmoni Corporation vừa công bố bản phân tích thị trường chứng khoán toàn cầu của mình.',
    vocabulary: ['release (v): công bố, phát hành', 'analysis (n): bản phân tích', 'stock market (n): thị trường chứng khoán'],
  },
  {
    questionNo: 118,
    part: 5,
    question: "Liu's Foods is pleased to reveal the _____ product in its famous soup line: pumpkin soup.",
    options: [
      { letter: 'A', text: 'popularity of' },
      { letter: 'B', text: 'as popular as' },
      { letter: 'C', text: 'most popular' },
      { letter: 'D', text: 'popular than' },
    ],
    answer: 'C',
    explanation: 'Sau "the" và trước danh từ "product" cần cụm tính từ. "The most popular product" là dạng so sánh nhất, nghĩa là sản phẩm phổ biến nhất. "Popular than" thiếu "more", "as popular as" cần đối tượng so sánh phía sau, "popularity of" là cụm danh từ không bổ nghĩa trực tiếp cho "product".',
    translation: 'Liu\'s Foods hân hạnh tiết lộ sản phẩm phổ biến nhất trong dòng súp nổi tiếng của hãng: súp bí đỏ.',
    vocabulary: ['reveal (v): tiết lộ', 'popular (adj): phổ biến', 'soup line (n): dòng sản phẩm súp'],
  },
  {
    questionNo: 119,
    part: 5,
    question: 'The proposed city budget outlines various projects, _____ renovations of the Fessler Road fire station.',
    options: [
      { letter: 'A', text: 'these' },
      { letter: 'B', text: 'including' },
      { letter: 'C', text: 'even though' },
      { letter: 'D', text: 'always' },
    ],
    answer: 'B',
    explanation: 'Sau dấu phẩy là một ví dụ nằm trong nhóm "various projects". "Including" nghĩa là bao gồm, dùng để giới thiệu ví dụ/thành phần được kể thêm. Các đáp án còn lại không nối được cụm danh từ "renovations..." với ý trước.',
    translation: 'Ngân sách thành phố được đề xuất phác thảo nhiều dự án, bao gồm việc cải tạo trạm cứu hỏa đường Fessler.',
    vocabulary: ['proposed budget (n): ngân sách đề xuất', 'outline (v): phác thảo', 'renovation (n): sự cải tạo'],
  },
  {
    questionNo: 120,
    part: 5,
    question: 'The _____ opening of the new bakery had to be postponed when a pipe burst in the kitchen.',
    options: [
      { letter: 'A', text: 'scheduled' },
      { letter: 'B', text: 'maintained' },
      { letter: 'C', text: 'motivated' },
      { letter: 'D', text: 'experienced' },
    ],
    answer: 'A',
    explanation: 'Chỗ trống bổ nghĩa cho danh từ "opening". "Scheduled opening" nghĩa là buổi khai trương đã được lên lịch. Vì một đường ống bị vỡ nên buổi khai trương theo lịch phải hoãn lại.',
    translation: 'Buổi khai trương đã được lên lịch của tiệm bánh mới phải hoãn lại khi một đường ống bị vỡ trong bếp.',
    vocabulary: ['opening (n): buổi khai trương', 'postpone (v): hoãn', 'pipe burst: đường ống bị vỡ'],
  },
  {
    questionNo: 121,
    part: 5,
    question: 'Two associates in the accounting department are being _____ for promotions.',
    options: [
      { letter: 'A', text: 'consider' },
      { letter: 'B', text: 'considerable' },
      { letter: 'C', text: 'considered' },
      { letter: 'D', text: 'consideration' },
    ],
    answer: 'C',
    explanation: 'Cấu trúc "are being + V3" là bị động tiếp diễn. Hai cộng sự đang được xem xét để thăng chức, nên cần phân từ quá khứ "considered". Các đáp án còn lại không hoàn thành cấu trúc bị động.',
    translation: 'Hai cộng sự trong bộ phận kế toán đang được xem xét để thăng chức.',
    vocabulary: ['associate (n): cộng sự', 'accounting department (n): phòng kế toán', 'promotion (n): sự thăng chức'],
  },
  {
    questionNo: 122,
    part: 5,
    question: '_____ the rock band Captain Zino decided to offer free tickets to their concert, sales of their album have reached record numbers.',
    options: [
      { letter: 'A', text: 'Since' },
      { letter: 'B', text: 'Besides' },
      { letter: 'C', text: 'As much as' },
      { letter: 'D', text: 'Not only' },
    ],
    answer: 'A',
    explanation: 'Mệnh đề chính dùng hiện tại hoàn thành "have reached", và mệnh đề đầu nêu mốc bắt đầu trong quá khứ. "Since" nghĩa là kể từ khi, rất hợp với hiện tại hoàn thành. Các lựa chọn khác không tạo quan hệ thời gian phù hợp.',
    translation: 'Kể từ khi ban nhạc rock Captain Zino quyết định tặng vé miễn phí cho buổi hòa nhạc, doanh số album của họ đã đạt mức kỷ lục.',
    vocabulary: ['rock band (n): ban nhạc rock', 'album sales (n): doanh số album', 'record numbers: con số kỷ lục'],
  },
  {
    questionNo: 123,
    part: 5,
    question: '_____ her interview, the committee agreed that Ms. Han was the best candidate for the supervisor job.',
    options: [
      { letter: 'A', text: 'As in' },
      { letter: 'B', text: 'Just as' },
      { letter: 'C', text: 'Almost' },
      { letter: 'D', text: 'After' },
    ],
    answer: 'D',
    explanation: 'Sau chỗ trống là cụm danh từ "her interview", nên cần giới từ/cụm nối phù hợp. "After her interview" nghĩa là sau cuộc phỏng vấn của cô ấy. Các đáp án khác không diễn tả trình tự thời gian phù hợp.',
    translation: 'Sau cuộc phỏng vấn của cô ấy, ủy ban đồng ý rằng cô Han là ứng viên tốt nhất cho vị trí giám sát viên.',
    vocabulary: ['interview (n): cuộc phỏng vấn', 'committee (n): ủy ban', 'candidate (n): ứng viên'],
  },
  {
    questionNo: 124,
    part: 5,
    question: "After monitoring the Hasher Corporation's inventory control process _____ several days, the consultant identified the problem.",
    options: [
      { letter: 'A', text: 'among' },
      { letter: 'B', text: 'except' },
      { letter: 'C', text: 'off' },
      { letter: 'D', text: 'for' },
    ],
    answer: 'D',
    explanation: 'Cụm thời gian "several days" cần giới từ "for" để chỉ khoảng thời gian kéo dài. "For several days" nghĩa là trong vài ngày. Các giới từ còn lại không diễn tả khoảng thời gian theo cách này.',
    translation: 'Sau khi theo dõi quy trình kiểm soát hàng tồn kho của Hasher Corporation trong vài ngày, nhà tư vấn đã xác định được vấn đề.',
    vocabulary: ['monitor (v): theo dõi', 'inventory control (n): kiểm soát hàng tồn kho', 'consultant (n): nhà tư vấn'],
  },
  {
    questionNo: 125,
    part: 5,
    question: 'Crane operators must check that all moving parts of the machine are fastened _____ before use.',
    options: [
      { letter: 'A', text: 'security' },
      { letter: 'B', text: 'securely' },
      { letter: 'C', text: 'secures' },
      { letter: 'D', text: 'securing' },
    ],
    answer: 'B',
    explanation: 'Chỗ trống bổ nghĩa cho động từ bị động "are fastened", nên cần trạng từ. "Securely" nghĩa là một cách chắc chắn/an toàn. "Security" là danh từ, còn "secures/securing" là dạng động từ.',
    translation: 'Người vận hành cần trục phải kiểm tra rằng tất cả các bộ phận chuyển động của máy được gắn chắc chắn trước khi sử dụng.',
    vocabulary: ['crane (n): cần trục', 'operator (n): người vận hành', 'fasten (v): buộc, gắn chặt'],
  },
  {
    questionNo: 126,
    part: 5,
    question: 'Use this coupon to _____ a free quote for cloud storage services.',
    options: [
      { letter: 'A', text: 'advertise' },
      { letter: 'B', text: 'discount' },
      { letter: 'C', text: 'develop' },
      { letter: 'D', text: 'obtain' },
    ],
    answer: 'D',
    explanation: 'Sau "to" cần động từ nguyên mẫu. Về nghĩa, dùng coupon để "obtain a free quote" là nhận/có được báo giá miễn phí. Các động từ còn lại không hợp với tân ngữ "a free quote".',
    translation: 'Hãy dùng phiếu giảm giá này để nhận báo giá miễn phí cho dịch vụ lưu trữ đám mây.',
    vocabulary: ['coupon (n): phiếu giảm giá', 'quote (n): báo giá', 'cloud storage (n): lưu trữ đám mây'],
  },
  {
    questionNo: 127,
    part: 5,
    question: 'By testing the _____ of the vehicle in desert terrain, the designers proved that it works perfectly in harsh conditions.',
    options: [
      { letter: 'A', text: 'enduring' },
      { letter: 'B', text: 'endurance' },
      { letter: 'C', text: 'endures' },
      { letter: 'D', text: 'endure' },
    ],
    answer: 'B',
    explanation: 'Sau mạo từ "the" và trước cụm "of the vehicle" cần một danh từ chính. "Endurance" là danh từ nghĩa là khả năng chịu đựng/sức bền. Các đáp án còn lại là dạng động từ hoặc V-ing.',
    translation: 'Bằng cách thử nghiệm độ bền của phương tiện trên địa hình sa mạc, các nhà thiết kế chứng minh rằng nó hoạt động hoàn hảo trong điều kiện khắc nghiệt.',
    vocabulary: ['endurance (n): sức bền, khả năng chịu đựng', 'terrain (n): địa hình', 'harsh condition (n): điều kiện khắc nghiệt'],
  },
  {
    questionNo: 128,
    part: 5,
    question: "The flashing yellow light serves as an _____ that the camera's battery needs to be charged.",
    options: [
      { letter: 'A', text: 'example' },
      { letter: 'B', text: 'allowance' },
      { letter: 'C', text: 'alert' },
      { letter: 'D', text: 'administration' },
    ],
    answer: 'C',
    explanation: 'Đèn vàng nhấp nháy có chức năng báo hiệu pin cần sạc. "Alert" là cảnh báo/tín hiệu báo động, hợp với cấu trúc "serves as an...". Các danh từ còn lại không hợp nghĩa.',
    translation: 'Đèn vàng nhấp nháy đóng vai trò như một cảnh báo rằng pin của máy ảnh cần được sạc.',
    vocabulary: ['flashing (adj): nhấp nháy', 'alert (n): cảnh báo', 'charge (v): sạc pin'],
  },
  {
    questionNo: 129,
    part: 5,
    question: 'Ms. Rosen did not say _____ about the plans for a new employee break room.',
    options: [
      { letter: 'A', text: 'several' },
      { letter: 'B', text: 'anything' },
      { letter: 'C', text: 'each' },
      { letter: 'D', text: 'someone' },
    ],
    answer: 'B',
    explanation: 'Trong câu phủ định với "did not say", đại từ phù hợp là "anything" nghĩa là bất cứ điều gì. "Several" và "each" cần danh từ phía sau, "someone" chỉ người và không hợp với động từ "say" trong nghĩa này.',
    translation: 'Bà Rosen không nói gì về kế hoạch cho phòng nghỉ nhân viên mới.',
    vocabulary: ['break room (n): phòng nghỉ', 'plan (n): kế hoạch', 'anything: bất cứ điều gì'],
  },
  {
    questionNo: 130,
    part: 5,
    question: 'Revenue growth exceeding 2 percent was seen _____ all business segments this quarter.',
    options: [
      { letter: 'A', text: 'across' },
      { letter: 'B', text: 'into' },
      { letter: 'C', text: 'prior to' },
      { letter: 'D', text: 'above' },
    ],
    answer: 'A',
    explanation: '"Across all business segments" nghĩa là trên khắp/tất cả các mảng kinh doanh. Câu muốn nói mức tăng trưởng doanh thu trên 2% xuất hiện ở mọi mảng trong quý này. Các giới từ còn lại không diễn tả phạm vi bao phủ như vậy.',
    translation: 'Tăng trưởng doanh thu vượt 2 phần trăm được ghi nhận ở tất cả các mảng kinh doanh trong quý này.',
    vocabulary: ['revenue (n): doanh thu', 'business segment (n): mảng kinh doanh', 'quarter (n): quý'],
  },
];

export const BUILT_IN_PART5_PRACTICE_TESTS = [
  {
    id: PART5_PRACTICE_TEST_ID,
    title: PART5_PRACTICE_TEST_TITLE,
    questions: PART5_PRACTICE_SET_01,
  },
  {
    id: PART5_2022_TEST_3_ID,
    title: PART5_2022_TEST_3_TITLE,
    questions: PART5_2022_TEST_3_SET,
  },
  {
    id: PART5_2022_TEST_4_ID,
    title: PART5_2022_TEST_4_TITLE,
    questions: PART5_2022_TEST_4_SET,
  },
];
